name: Release workflow
run-name: ${{ github.actor }} triggered Release workflow

on:
  push:
    branches:
      - "release/*"

jobs:
  build-preprod:
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      environment: preprod
      chart_path: chart/cohort-nlp/Chart.yaml
    secrets: inherit

  build-prod:
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      environment: prod
      chart_path: chart/cohort-nlp/Chart.yaml
    secrets: inherit